### PR TITLE
Add quarkus-opentelemetry-exporter

### PR DESCRIPTION
**Pull request by brunobat**

### CODE REVIEW

**Review by gastaldi — CHANGES_REQUESTED** [review]
Please keep in alphabetical order

**Comment by gastaldi** [comment]
Also it failed with 

```
15:45:36.424] FATAL (antora): Duplicate nav in dev@quarkus-opentelemetry-exporter: modules/ROOT/nav.adoc
    1: docs/modules/ROOT/nav.adoc in https://github.com/quarkiverse/quarkus-opentelemetry-exporter.git (branch: 1.x | start path: docs)
    2: docs/modules/ROOT/nav.adoc in https://github.com/quarkiverse/quarkus-opentelemetry-exporter.git (branch: main | start path: docs)
Add the --stacktrace option to see the cause of the error.
Error: Process completed with exit code 1.
```

**Comment by brunobat** [comment]
Will update @gastaldi

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Don't forget to update the nav branch on 1.x 👍🏻

**Pull request merged**
