### PR TITLE
Add File Vault

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by gastaldi** [comment]
Build failed: 
```
Error: Duplicate nav in dev@quarkus-kerberos: modules/ROOT/nav.adoc
  1: docs/modules/ROOT/nav.adoc in [quarkiverse/quarkus-kerberos](https://github.com/quarkiverse/quarkus-kerberos) (ref: main)
  2: docs/modules/ROOT/nav.adoc in [quarkiverse/quarkus-file-vault](https://github.com/quarkiverse/quarkus-file-vault) (ref: main)
```

**Comment by sberyozkin** [comment]
Sorry, copy and paste

**Comment by sberyozkin** [comment]
I think I fixed it, but I'm not seeing an option to restart in the failed job, please restart

**Comment by sberyozkin** [comment]
Hmm, I'm not sure I understand the problem

https://github.com/quarkiverse/quarkus-file-vault/blob/main/docs/modules/ROOT/nav.adoc
https://github.com/quarkiverse/quarkus-kerberos/blob/main/docs/modules/ROOT/nav.adoc

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by sberyozkin** [comment]
thanks

**Pull request merged**
