### PR TITLE
Add comment to PR with preview link

### PR DESCRIPTION
**Pull request by holly-cummins**
I noticed we're not adding comments to PRs, even though we do the hard work of making a preview.

### CODE REVIEW

**Comment by holly-cummins** [comment]
Sadly, the version of the workflow run in the PR is the one in main, not in this PR, so I'm not sure we can test it without merging.

**Comment by gastaldi** [comment]
This is weird. Can you check if the comment is created for a PR coming from a branch from this repository (not from a fork?).

AFAIR the surge-action already does all the work, so if we're using it I don't think it needs extra steps

**Comment by holly-cummins** [comment]
I agree that the [docs](https://github.com/marketplace/actions/surge-pr-preview) show pictures of comments, which makes it look like the action does everything. In https://github.com/quarkusio/quarkusio.github.io/blob/develop/.github/workflows/preview.yml we have to add the comments manually, but we're not using the action, just a `npx` command, so that makes sense. 

Unfortunately, I don't think I have permissions to do a PR from a branch of this repo. I agree it's a good experiment to try. 

 Oh wait, I think I see the issue. 
 
 ```
     permissions:
      pull-requests: write # allow surge-preview to create/update PR comments
 ```
 
 I'll try adding that instead.

**Comment by gastaldi** [comment]
Let's see how that goes

**Comment by gastaldi** [comment]
> since most PRs will be from forks

I don't think so, as members of the `quarkiverse-members` team are allowed to push and create branches here

**Comment by holly-cummins** [comment]
> > since most PRs will be from forks
> 
> I don't think so, as members of the `quarkiverse-members` team are allowed to push and create branches here

Oh, that would help! 

I just did a quick survey of the recent PRs to check. 
- https://github.com/quarkiverse/quarkiverse-docs/pull/85 - fork, no comment
- https://github.com/quarkiverse/quarkiverse-docs/pull/84, main repo, comment 
- https://github.com/quarkiverse/quarkiverse-docs/pull/83, main repo, comment
- https://github.com/quarkiverse/quarkiverse-docs/pull/82, main repo, comment
- https://github.com/quarkiverse/quarkiverse-docs/pull/81, main repo, comment
- https://github.com/quarkiverse/quarkiverse-docs/pull/80, main repo, comment
- https://github.com/quarkiverse/quarkiverse-docs/pull/78, main repo, comment

So the first one I checked was from a fork, but all the others were from the main repo. I guess it's just Peter and I who hadn't got the memo. And my change didn't really do anything. :)

Scrolling down further I can find a few others from forks, like https://github.com/quarkiverse/quarkiverse-docs/pull/63 and https://github.com/quarkiverse/quarkiverse-docs/pull/64, but not so many. So I guess that's ok.

**Comment by holly-cummins** [comment]
(Another of way of checking, I guess, is to see that we have 31 forks of this repo, and 89 PRs. So if every fork did exactly one PR, that would be a third of the PRs originating from a fork ... but some of those forks probably didn't originate any PRs.)

**Comment by gastaldi** [comment]
I wonder if splitting the CI preview as proposed in https://github.com/quarkiverse/quarkiverse-docs/issues/44 would help

**Comment by holly-cummins** [comment]
I think so. The main quarkus docs site, and extensions.quarkus.io, have previews from forks, using a similar technique, I think. 

While I was reading the surge docs I also noticed that we should be able to have just one surge workflow. If we trigger on both open and close, and set `teardown: true`, it seems like surge will figure out whether to standup or teardown.

**Pull request merged**
