### PR TITLE
add quarkus-dapr docs

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by gastaldi** [comment]
Nice! Thanks for fixing the doc title :wink

**Comment by zhfeng** [comment]
@gastaldi I released `quarkus-dapr:1.0.0` yesterday. So it will be included in quarkus platform with the next quarkus release and available on https://code.quarkus.io?

**Comment by gastaldi** [comment]
@zhfeng to make it available in code.quarkus and our tooling, you need to register it in the Quarkus extension catalog: https://github.com/quarkiverse/quarkiverse/wiki/Checklist#make-your-extension-available-in-the-tooling

**Comment by zhfeng** [comment]
Nice, I will check it.

**Pull request merged**
