### PR TITLE
Fix syntax error (maybe) in alphabetise workflow

### PR DESCRIPTION
**Pull request by holly-cummins**
Not sure I could spot the error, but I've tidied up the indenting, which hopefully will fix it.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by holly-cummins** [comment]
Ah, I made the same changes as #175. Because the yaml file isn't changing, we won't get a new run of the action for some time. I'll do a manual dispatch to try and confirm it's ok.

**Comment by holly-cummins** [comment]
The good news is that `yq` is installed, so @gastaldi was right, @gsmet. 

The bad news is I don't have the git commands right:

```
Run git checkout -b alpha-10308937259
Switched to a new branch 'alpha-10308937259'
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@fv-az575-72.txkdwr3xd4ruhezurzmahy12zg.cx.internal.cloudapp.net>) not allowed
```

**Comment by gastaldi** [comment]
Ah you need this: https://github.com/quarkiverse/quarkus-ironjacamar/blob/main/.github/workflows/release.yml#L45-L48

**Comment by holly-cummins** [comment]
I've done something similar in https://github.com/quarkiverse/quarkiverse-docs/pull/177. Not sure if the actor variable or hardcoded is better.

**Pull request merged**
