### PR TITLE
 Added v* to list of quarkus-cxf branches

### PR DESCRIPTION
**Pull request by shumonsharif**
Fixes https://github.com/quarkiverse/quarkus-cxf/issues/220

### CODE REVIEW

**Comment by gastaldi** [comment]
The build fails with

```
Error: Duplicate nav in dev@quarkus-cxf: modules/ROOT/nav.adoc
  1: docs/modules/ROOT/nav.adoc in https://github.com/quarkiverse/quarkus-cxf.git (ref: master)
  2: docs/modules/ROOT/nav.adoc in https://github.com/quarkiverse/quarkus-cxf.git (ref: v0.7)
```

Need to investigate what's wrong

**Comment by shumonsharif** [comment]
OK, I'm trying to look into it as well now.

**Comment by shumonsharif** [comment]
@gastaldi I think I fixed the issue; could you please try a new build?

**Comment by shumonsharif** [comment]
I keep forgetting that the builds for the docs aren't automated ... will be sure to test the full build locally first going forward!

**Review by gastaldi — APPROVED** [review]
I tested locally and it works. I'll introduce PR builds in this repository

**Comment by gastaldi** [comment]
@shumonsharif Builds in this repository are now automated (and deployed to surge.sh for a quick preview). Enjoy!

**Pull request merged**
