### PR TITLE
Add the Quarkus Kiota extension

### PR DESCRIPTION
**Pull request by andreaTP**
Reference: https://github.com/quarkusio/quarkus/issues/37843

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Kept in alphabetical order, nice

**Comment by maxandersen** [comment]
sorry for missing this but this should be rolled back IMO. see #139

**Comment by maxandersen** [comment]
@andreaTP sorry for that - as you have the content externally is there somewhere you can serve the content ?

**Comment by andreaTP** [comment]
I can set GH Pages if needed, but I'm more interested in complying with:

> you are on quarkiverse hub because there we have backup/access to maintain if maintainer goes away

I think I can separate the `quarkus-extension` from the repo, it has downsides, but I can live with it and we can discuss the nuances.

**Comment by gastaldi** [comment]
Just a friendly reminder that if the quarkus-extension lives in the Quarkiverse hub, the groupId must be renamed to `io.quarkiverse.kiota`

**Comment by holly-cummins** [comment]
> Just a friendly reminder that if the quarkus-extension lives in the Quarkiverse hub, the groupId must be renamed to `io.quarkiverse.kiota`

I'd forgotten that bit, but I've just confirmed it's documented at https://hub.quarkiverse.io/#projects-maven-artifact-groupids.

**Comment by andreaTP** [comment]
> Just a friendly reminder that if the quarkus-extension lives in the Quarkiverse hub, the groupId must be renamed to `io.quarkiverse.kiota`

It applies only to the Quarkus extension, I'm fine with that, thanks for the heads up 👍

**Comment by andreaTP** [comment]
Where to go from here?
Should I submit another request to have a `quarkus-kiota` repo in the `quarkiverse` org?

**Comment by gastaldi** [comment]
I'll set up a repo for you in the quarkiverse-devops repo

**Pull request merged**
