### PR TITLE
Add Google Cloud Services documentation

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by gastaldi** [comment]
@loicmathieu it shows a Page not found. I think your docs structure is missing a `modules` subdirectory?

**Comment by gastaldi** [comment]
I'm closing this PR to trigger the surge.sh redeployment when it's reopened.

**Comment by loicmathieu** [comment]
@gastaldi fixed, can you re-open the PR please ?

**Review by gastaldi — APPROVED** [review]
Looks great now 😉

**Pull request merged**
